apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-task-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ujjwalkumarcs054-star/ai-task-platform-infra.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-task-platform
  syncPolicy:
    automated:
      prune: true      # remove resources deleted from git
      selfHeal: true    # revert manual cluster drift back to git state
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
